
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.ViewWidgets.DialogueScriptWidgets
{
	public partial class DialogueCounterpartyWidget
	{
		private global::Gtk.VBox vbox1;

		private global::Gamma.Widgets.yEntryReferenceVM referenceClient;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.ViewWidgets.DialogueScriptWidgets.DialogueCounterpartyWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.ViewWidgets.DialogueScriptWidgets.DialogueCounterpartyWidget";
			// Container child Vodovoz.ViewWidgets.DialogueScriptWidgets.DialogueCounterpartyWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.referenceClient = new global::Gamma.Widgets.yEntryReferenceVM();
			this.referenceClient.Events = ((global::Gdk.EventMask)(256));
			this.referenceClient.Name = "referenceClient";
			this.vbox1.Add(this.referenceClient);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.referenceClient]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.referenceClient.Changed += new global::System.EventHandler(this.OnReferenceClientChanged);
		}
	}
}
