
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.JournalViewers.WageCalculation
{
	public partial class WageParametersView
	{
		private global::Gtk.Table table4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTreeView ytwParameters;

		private global::Gtk.HBox hbox4;

		private global::QSOrmProject.EnumMenuButton ebtnAddParameter;

		private global::Gtk.Button btnEdit;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.JournalViewers.WageCalculation.WageParametersView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.JournalViewers.WageCalculation.WageParametersView";
			// Container child Vodovoz.JournalViewers.WageCalculation.WageParametersView.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytwParameters = new global::Gamma.GtkWidgets.yTreeView();
			this.ytwParameters.CanFocus = true;
			this.ytwParameters.Name = "ytwParameters";
			this.GtkScrolledWindow.Add(this.ytwParameters);
			this.table4.Add(this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table4[this.GtkScrolledWindow]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			// Container child table4.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.ebtnAddParameter = new global::QSOrmProject.EnumMenuButton();
			this.ebtnAddParameter.CanFocus = true;
			this.ebtnAddParameter.Name = "ebtnAddParameter";
			this.ebtnAddParameter.UseUnderline = true;
			this.ebtnAddParameter.UseMarkup = false;
			this.ebtnAddParameter.Label = global::Mono.Unix.Catalog.GetString("Добавить параметр");
			this.hbox4.Add(this.ebtnAddParameter);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.ebtnAddParameter]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnEdit = new global::Gtk.Button();
			this.btnEdit.CanFocus = true;
			this.btnEdit.Name = "btnEdit";
			this.btnEdit.UseUnderline = true;
			this.btnEdit.Label = global::Mono.Unix.Catalog.GetString("Изменить...");
			this.hbox4.Add(this.btnEdit);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnEdit]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.table4.Add(this.hbox4);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table4[this.hbox4]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.table4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
