
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.ViewWidgets.DialogueScriptWidgets
{
	public partial class DialogueNewOrderWidget
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button buttonNewOrder;

		private global::Gtk.Button buttonRepeateOrder;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.ViewWidgets.DialogueScriptWidgets.DialogueNewOrderWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.ViewWidgets.DialogueScriptWidgets.DialogueNewOrderWidget";
			// Container child Vodovoz.ViewWidgets.DialogueScriptWidgets.DialogueNewOrderWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonNewOrder = new global::Gtk.Button();
			this.buttonNewOrder.CanFocus = true;
			this.buttonNewOrder.Name = "buttonNewOrder";
			this.buttonNewOrder.UseUnderline = true;
			this.buttonNewOrder.Label = global::Mono.Unix.Catalog.GetString("Новый заказ");
			this.hbox1.Add(this.buttonNewOrder);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonNewOrder]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonRepeateOrder = new global::Gtk.Button();
			this.buttonRepeateOrder.CanFocus = true;
			this.buttonRepeateOrder.Name = "buttonRepeateOrder";
			this.buttonRepeateOrder.UseUnderline = true;
			this.buttonRepeateOrder.Label = global::Mono.Unix.Catalog.GetString("Повторить зказ");
			this.hbox1.Add(this.buttonRepeateOrder);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonRepeateOrder]));
			w2.Position = 2;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			this.Add(this.vbox1);
			if((this.Child != null)) {
				this.Child.ShowAll();
			}
			this.Hide();
			this.buttonNewOrder.Clicked += new global::System.EventHandler(this.OnButtonNewOrderClicked);
			this.buttonRepeateOrder.Clicked += new global::System.EventHandler(this.OnButtonRepeateOrderClicked);
		}
	}
}
