
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Dialogs.WageCalculation
{
	public partial class WageCalcParametersDlg
	{
		private global::Gtk.Table table1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTreeView ytwAnotherParameters;

		private global::Gtk.HBox hbxSaveCancel;

		private global::Gtk.Button buttonSave;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Table tblCurrentParameter;

		private global::Gamma.Widgets.yEnumComboBox enumCmbName;

		private global::Gtk.Label lblName;

		private global::Gtk.Label lblPeriodStart;

		private global::Gtk.Label lblValue;

		private global::Gamma.Widgets.yDatePicker ydtPeriodStart;

		private global::Gamma.GtkWidgets.yEntry yentValue;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Dialogs.WageCalculation.WageCalcParametersDlg
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Dialogs.WageCalculation.WageCalcParametersDlg";
			// Container child Vodovoz.Dialogs.WageCalculation.WageCalcParametersDlg.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytwAnotherParameters = new global::Gamma.GtkWidgets.yTreeView();
			this.ytwAnotherParameters.CanFocus = true;
			this.ytwAnotherParameters.Name = "ytwAnotherParameters";
			this.GtkScrolledWindow.Add(this.ytwAnotherParameters);
			this.table1.Add(this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.GtkScrolledWindow]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.hbxSaveCancel = new global::Gtk.HBox();
			this.hbxSaveCancel.Name = "hbxSaveCancel";
			this.hbxSaveCancel.Spacing = 6;
			// Container child hbxSaveCancel.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.Menu);
			this.buttonSave.Image = w3;
			this.hbxSaveCancel.Add(this.buttonSave);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbxSaveCancel[this.buttonSave]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbxSaveCancel.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Отменить");
			global::Gtk.Image w5 = new global::Gtk.Image();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w5;
			this.hbxSaveCancel.Add(this.buttonCancel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbxSaveCancel[this.buttonCancel]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.table1.Add(this.hbxSaveCancel);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.hbxSaveCancel]));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tblCurrentParameter = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.tblCurrentParameter.Name = "tblCurrentParameter";
			this.tblCurrentParameter.RowSpacing = ((uint)(6));
			this.tblCurrentParameter.ColumnSpacing = ((uint)(6));
			// Container child tblCurrentParameter.Gtk.Table+TableChild
			this.enumCmbName = new global::Gamma.Widgets.yEnumComboBox();
			this.enumCmbName.Name = "enumCmbName";
			this.enumCmbName.ShowSpecialStateAll = false;
			this.enumCmbName.ShowSpecialStateNot = false;
			this.enumCmbName.UseShortTitle = false;
			this.enumCmbName.DefaultFirst = false;
			this.tblCurrentParameter.Add(this.enumCmbName);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tblCurrentParameter[this.enumCmbName]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCurrentParameter.Gtk.Table+TableChild
			this.lblName = new global::Gtk.Label();
			this.lblName.Name = "lblName";
			this.lblName.Xalign = 1F;
			this.lblName.LabelProp = global::Mono.Unix.Catalog.GetString("Имя параметра:");
			this.tblCurrentParameter.Add(this.lblName);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblCurrentParameter[this.lblName]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCurrentParameter.Gtk.Table+TableChild
			this.lblPeriodStart = new global::Gtk.Label();
			this.lblPeriodStart.Name = "lblPeriodStart";
			this.lblPeriodStart.Xalign = 1F;
			this.lblPeriodStart.LabelProp = global::Mono.Unix.Catalog.GetString("Дата начала действия параметра:");
			this.tblCurrentParameter.Add(this.lblPeriodStart);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tblCurrentParameter[this.lblPeriodStart]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCurrentParameter.Gtk.Table+TableChild
			this.lblValue = new global::Gtk.Label();
			this.lblValue.Name = "lblValue";
			this.lblValue.Xalign = 1F;
			this.lblValue.LabelProp = global::Mono.Unix.Catalog.GetString("Значение параметра:");
			this.tblCurrentParameter.Add(this.lblValue);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tblCurrentParameter[this.lblValue]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCurrentParameter.Gtk.Table+TableChild
			this.ydtPeriodStart = new global::Gamma.Widgets.yDatePicker();
			this.ydtPeriodStart.Events = ((global::Gdk.EventMask)(256));
			this.ydtPeriodStart.Name = "ydtPeriodStart";
			this.ydtPeriodStart.WithTime = false;
			this.ydtPeriodStart.Date = new global::System.DateTime(0);
			this.ydtPeriodStart.IsEditable = false;
			this.ydtPeriodStart.AutoSeparation = false;
			this.tblCurrentParameter.Add(this.ydtPeriodStart);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblCurrentParameter[this.ydtPeriodStart]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblCurrentParameter.Gtk.Table+TableChild
			this.yentValue = new global::Gamma.GtkWidgets.yEntry();
			this.yentValue.CanFocus = true;
			this.yentValue.Name = "yentValue";
			this.yentValue.IsEditable = true;
			this.yentValue.InvisibleChar = '•';
			this.tblCurrentParameter.Add(this.yentValue);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblCurrentParameter[this.yentValue]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table1.Add(this.tblCurrentParameter);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.tblCurrentParameter]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.table1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
