
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.ViewWidgets.DialogueScriptWidgets
{
	public partial class DialogueBaseWidget
	{
		private global::Gtk.VBox vboxContainer;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.ViewWidgets.DialogueScriptWidgets.DialogueBaseWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.ViewWidgets.DialogueScriptWidgets.DialogueBaseWidget";
			// Container child Vodovoz.ViewWidgets.DialogueScriptWidgets.DialogueBaseWidget.Gtk.Container+ContainerChild
			this.vboxContainer = new global::Gtk.VBox();
			this.vboxContainer.Name = "vboxContainer";
			this.vboxContainer.Spacing = 6;
			this.Add(this.vboxContainer);
			if((this.Child != null)) {
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
